### ISSUE TITLE
Remove .DS_Store

### ISSUE THREAD

**Issue by YashKumarVerma** [mexili/ini-rs#4]

**Comment by HarshitAditya27** [comment]
Hi, I would like to work on this issue and I am contributing under MWoC (Mexili Org), I just need to remove the.DS_Store file?

**Comment by QEDK** [comment]
> 
> 
> Hi, I would like to work on this issue and I am contributing under MWoC (Mexili Org), I just need to remove the.DS_Store file?

Yes, please use proper commit messages when doing so.

**Comment by HarshitAditya27** [comment]
Sir, in which branch I have to make PR?

**Comment by QEDK** [comment]
Create a fork and make a PR.

**Comment by HarshitAditya27** [comment]
Ok, sir got it.

**Comment by HarshitAditya27** [comment]
Sir, I will be using "Removed .DS_Store" as the commit message, is that okay?

**Comment by QEDK** [comment]
No need to address me as sir! Please use present tense in the commit, apart
from that it's good.

**Comment by HarshitAditya27** [comment]
Ok got it
